SELECT COUNT(DISTINCT O_TOTALPRICE)
FROM ORDERS;

SELECT * 
FROM CUSTOMER JOIN ORDERS
              ON CUSTOMER.C_CUSTKEY = ORDERS.O_CUSTKEY
WHERE C_ACCTBAL = 1000 AND O_TOTALPRICE = 1000;

SELECT * 
FROM ORDERS JOIN LINEITEM
            ON ORDERS.O_ORDERKEY = LINEITEM.L_ORDERKEY
WHERE O_ORDERDATE = '09-SEP-2021' OR L_QUANTITY = 500;

SELECT *
FROM LINEITEM JOIN PART
              ON LINEITEM.L_PARTKEY = PART.P_PARTKEY
WHERE L_QUANTITY = 100 AND P_NAME = 'bolt';

SELECT COUNT(PS_AVAILQTY)
FROM PARTSUPP JOIN LINEITEM
              ON PARTSUPP.PS_PARTKEY = LINEITEM.L_PARTKEY
	      JOIN ORDERS
	      ON LINEITEM.L_ORDERKEY = ORDERS.O_ORDERKEY
WHERE O_ORDERSTATUS = 'F' AND L_QUANTITY > 200 AND PS_SUPPLYCOST > 100;


					  
